version: "2.1"

jobs:
  test:
    parameters:
      py-version:
        description: "Python version"
        default: "3.6"
        type: string

    working_directory: ~/repo

    docker:
      - image: circleci/python:<< parameters.py-version >>

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-<< parameters.py-version >>-{{ checksum "pyproject.toml" }}-{{ checksum "poetry.lock" }}
          - v1-dependencies-<< parameters.py-version >>-{{ checksum "pyproject.toml" }}-
          - v1-dependencies-<< parameters.py-version >>-

      - run:
          name: Install Deps
          command: |
            sudo python3 -m pip install poetry
            poetry install
            poetry run python -m pip install codecov

      - save_cache:
          paths:
            - /home/circleci/.cache/pypoetry/virtualenvs
            - /root/.cache/pip
          key: v1-dependencies-<< parameters.py-version >>-{{ checksum "pyproject.toml" }}-{{ checksum "poetry.lock" }}

      - run:
          name: Lint
          command: |
            poetry run flake8 pytest_select
            poetry run black --check pytest_select tests

      - run:
          name: Run Rests
          command: |
            mkdir test-reports
            poetry run coverage run --branch --source=pytest_select -m py.test --junit-xml=test-reports/result.xml

      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports

      - restore_cache:
          keys:
          - v1-mutation-<< parameters.py-version >>

      - run:
          name: Run Mutation Tests
          command: |
            poetry run mutmut run --paths-to-mutate pytest_select --runner 'python -m pytest'
            poetry run python tests/util/mutmut_get_failed.py

      - save_cache:
          paths:
            - .mutmut-cache
          key: v1-mutation-<< parameters.py-version >>

      - run:
          name: upload codecov results
          command: poetry run codecov

workflows:
  default:
    jobs:
      - test:
          name: test-3.6
          py-version: "3.6"
      - test:
          name: test-3.7
          py-version: "3.7"
